title: "Shanghao Wu"
description: "B.S. in Mathematics @ Northeastern University · Graph Theory, ML"
url: "https://crushwu8.github.io"   # 保持你的域名
minimal_mistakes_skin: "dark"       # 可换 default/air/neon 等

author:
  name: "Shanghao Wu"
  avatar: "/images/image.jpg"      # 把头像放到 /images/avatar.jpg
  bio: "Math undergrad at Northeastern University (’26). Interested in combinatorics/graph theory and applied ML; experienced in tutoring and Olympiad grading."
  location: "Boston, MA"
  email: "wu.shangh@northeastern.edu"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/crushWu8"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/shanghaowu/"
